name: CI

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]

jobs:
  lint:
    name: Lint & Format
    runs-on: ubuntu-latest
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

    steps:
      - uses: actions/checkout@v6.0.2

      - uses: actions/setup-python@v6.2.0
        with:
          python-version: "3.12"

      - uses: astral-sh/setup-uv@v7.5.0

      - run: uv pip install --system ".[dev]"

      - run: ruff check .

      - run: black --check . --target-version py312

      - run: mypy pyfragment

  test:
    name: Tests
    runs-on: ubuntu-latest
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
      COOKIES_JSON: ${{ secrets.COOKIES_JSON }}

    steps:
      - uses: actions/checkout@v6.0.2

      - uses: actions/setup-python@v6.2.0
        with:
          python-version: "3.12"

      - uses: astral-sh/setup-uv@v7.5.0

      - run: uv pip install --system ".[dev]"

      - run: pytest
