name: Tests

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6.0.2

      - uses: actions/setup-python@v6.2.0
        with:
          python-version: "3.12"

      - name: Install uv
        uses: astral-sh/setup-uv@v7.5.0

      - name: Install dependencies
        run: uv pip install --system ".[dev]"

      - name: Write cookies.json
        if: ${{ env.COOKIES_JSON != '' }}
        run: echo "$COOKIES_JSON" > cookies.json
        env:
          COOKIES_JSON: ${{ secrets.COOKIES_JSON }}

      - name: Run tests
        run: pytest
